"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['imsg_stats.py']
DATA_FILES = ['index.html', 'scatter_new.js']
#OPTIONS = {'argv_emulation': True, "resources":["index.html"]}
OPTIONS = {'argv_emulation': True}

setup(
    name='charactr',
    py_modules=['contacts','chat_to_csv','imsg_stats'],
    version='0.0',
    description='Visualizing your iMessage data',
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
